dist: xenial
os: linux
language: php

# avoid double Travis build when the PR is created on upstream
if: |
    type = pull_request OR \
    branch = master

jobs:
    include:
        - php: 8.0
          env: SYMFONY_PHPUNIT_VERSION=7.5
    fast_finish: true
    allow_failures:
        - php: 8.0

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
    - if [ "$CS_FIXER" != "run" ]; then composer remove friendsofphp/php-cs-fixer --dev --no-progress --no-update ; fi;
    - composer update --prefer-dist --no-progress -o
    - php vendor/bin/simple-phpunit install

before_script:
    - mkdir -p build/logs

script:
    - php vendor/bin/simple-phpunit -v
